/**
 * Demo tasks, calendar events and team updates. Due dates and event times are relative to the load time so the
 * home page always shows a realistic mix: past-due, today, this week and next month.
 */
import type { CalendarEvent, Deposition, Task, TeamUpdate } from "@/lib/types/domain";
import { DEMO_CUSTODIANS, DEMO_DEPOSITIONS, DEMO_EXPERTS, DEMO_ID_PREFIX, DEMO_MATTERS, DEMO_TEAM } from "../ids";
import { at, businessDay, dayOffset, hoursAgo, type DemoBuildContext } from "./context";
import { DEMO_CUSTODIAN_NAMES, DEMO_OPPOSING_COUNSEL } from "./people";

const C = DEMO_MATTERS.consumer;
const J = DEMO_MATTERS.doj;
const A = DEMO_TEAM.associate;
const P = DEMO_TEAM.paralegal;

const ed = (view?: string) => `/ediscovery?matter=${C}${view ? `&view=${view}` : ""}`;
const lib = `/library?matter=${C}`;

type TaskSpec = Omit<Task, "id" | "createdAt" | "updatedAt" | "dueAt" | "assigneeId" | "createdById" | "matterId"> & { key: string; due: number; who: "owner" | "associate" | "paralegal"; by?: "owner" | "associate" | "paralegal"; matter?: "consumer" | "doj"; age: number };

const TASKS: TaskSpec[] = [
  // Past due
  { key: "rfp_deficiency", title: "Respond to defendant's deficiency letter on RFP Set One (custodian date ranges)", description: "Defense counsel's letter argues the 2016 start date for the App Store Policy custodians is overbroad. Draft a response tying the date range to the 2016–2018 anti-steering policy documents and offer to phase the Marsh and Ames collections.", due: -3, who: "associate", by: "owner", status: "in_progress", priority: "urgent", tags: ["meet-and-confer", "RFP"], source: "manual", age: 170 },
  { key: "privlog_challenge", title: "Challenge letter: 31 privilege-log entries with Hannah Cole merely copied", description: "Entries describe business discussions of commission tiers with in-house counsel only on cc. Group by category and cite the log numbers; request re-review or production.", due: -1, who: "associate", status: "todo", priority: "high", tags: ["privilege"], source: "manual", age: 96, links: [{ label: "Privilege log", href: ed("privilege") }] },
  { key: "okoro_errata", title: "Okoro deposition: cite-check the digest against the final transcript", description: "Confirm every page/line cite in the digest, especially the pass-through answer at 88:4 and its qualification at 142:3.", due: -2, who: "paralegal", by: "associate", status: "todo", priority: "high", tags: ["deposition", "errata"], source: "manual", age: 60, links: [{ label: "Depositions", href: ed("depositions") }] },
  { key: "hot_docs_week", title: "Weekly hot-document digest (App Store Policy custodians)", description: "Generated by the hot-document digest workflow; 14 documents newly coded hot. Needs attorney review before it goes to the team.", due: -4, who: "paralegal", status: "done", priority: "medium", tags: ["digest"], source: "workflow", age: 120 },
  // Today / this week
  { key: "reyes_outline", title: "Finalize Reyes deposition outline: tap-to-pay and NFC access", description: "The outline PDF is in Deposition Prep; its exhibit list comes from the Wallet & NFC documents in the production. Confirm Bates numbers against the production index before marking.", due: 0, who: "owner", by: "associate", status: "review", priority: "urgent", tags: ["deposition", "outline"], source: "manual", age: 72, links: [{ label: "Deposition outline (PDF)", href: lib }] },
  { key: "reyes_notice", title: "Serve deposition notice for Tomas Reyes (Wallet & NFC)", description: "Confirm date with defendant's counsel and serve the notice with the document schedule; coordinate with the tracked government action to avoid duplicative questioning.", due: 1, who: "paralegal", by: "owner", status: "todo", priority: "high", tags: ["deposition", "notice"], source: "manual", age: 30 },
  { key: "search_terms", title: "Negotiate supplemental search terms for the messaging custodians", description: "Hit report shows 'green bubble' and 'iMessage for Android' variants return 41k documents; propose proximity limiters before the meet-and-confer.", due: 2, who: "associate", status: "in_progress", priority: "high", tags: ["ESI", "search terms"], source: "manual", age: 48, links: [{ label: "E-discovery review", href: ed() }] },
  { key: "second_level", title: "Second-level review: Okoro payments custodial set", description: "QC first-level responsiveness and hot calls on the payments set, focusing on commission-rate analyses and the link-out entitlement documents.", due: 3, who: "paralegal", by: "associate", status: "in_progress", priority: "high", tags: ["review"], source: "manual", age: 80, links: [{ label: "Review queue", href: ed() }] },
  { key: "expert_data", title: "Deliver App Store transaction data extract to Dr. Varga's team", description: "Produced transaction-level data (anonymized) plus the data dictionary; confirm the protective-order acknowledgment is on file before transfer.", due: 4, who: "paralegal", by: "owner", status: "todo", priority: "medium", tags: ["expert", "data"], source: "manual", age: 20 },
  { key: "cmc_statement", title: "Draft joint case management statement (discovery status section)", description: "Status of document production, deposition schedule, and the open dispute over structured data. Circulate to defense counsel 3 days before the filing deadline.", due: 5, who: "associate", by: "owner", status: "todo", priority: "high", tags: ["CMC"], source: "docket", age: 40 },
  { key: "market_def_memo", title: "Partner review: market definition and anti-steering research memo", description: "Memo is in the matter folder. Confirm the smartphone vs. performance-smartphone framing and the treatment of the two-sided market question before it goes to the expert.", due: 2, who: "owner", by: "associate", status: "review", priority: "medium", tags: ["research", "memo"], source: "manual", age: 26, links: [{ label: "Matter folder", href: lib }] },
  { key: "conflict_followup", title: "Follow up on Okoro's Small Business Program timing testimony", description: "Okoro testified she first saw the modelling in November 2020 (101:4); Exhibit Okoro-10 is dated September 28, 2020. Review the conflicts view and decide whether to raise it with Ames.", due: 6, who: "associate", status: "todo", priority: "high", tags: ["conflicts"], source: "agent", age: 18, links: [{ label: "Conflicts", href: ed("conflicts") }] },
  // Next weeks / next month
  { key: "class_cert_outline", title: "Class certification brief: outline of predominance section", description: "Common impact via the uniform commission structure; tie to Dr. Varga's overcharge regression and pass-through analysis.", due: 12, who: "owner", status: "in_progress", priority: "high", tags: ["class certification"], source: "manual", age: 100 },
  { key: "varga_report", title: "Comment on Dr. Varga's draft overcharge report (v0.7)", description: "Check that every factual assertion has a Bates cite; confirm the but-for commission benchmark is sourced to produced documents or public filings.", due: 16, who: "associate", status: "todo", priority: "high", tags: ["expert"], source: "manual", age: 8 },
  { key: "damages_model_qc", title: "QC the damages workbook formulas (overcharge × volume by year)", description: "Reconcile yearly totals with the expert's backup and lock the input cells.", due: 10, who: "paralegal", by: "associate", status: "todo", priority: "medium", tags: ["damages"], source: "manual", age: 14 },
  { key: "ames_prep", title: "Prepare Ames deposition exhibit binder (developer relations)", description: "Developer outreach on link-out entitlement, super-app review notes, and the cloud-gaming catalog requirement.", due: 8, who: "paralegal", by: "owner", status: "todo", priority: "medium", tags: ["deposition", "exhibits"], source: "manual", age: 10 },
  { key: "structured_data_mtc", title: "Draft letter brief to compel structured transaction data", description: "Joint letter format under the standing order; five pages. Attach the meet-and-confer chronology.", due: 20, who: "associate", by: "owner", status: "todo", priority: "high", tags: ["motion to compel"], source: "manual", age: 6 },
  { key: "30b6_topics", title: "Serve Rule 30(b)(6) topics: commission structure, anti-steering enforcement, wallet access", due: 14, who: "associate", status: "todo", priority: "medium", tags: ["30(b)(6)"], source: "manual", age: 12, description: "Twelve topics; align with the government action's topics to limit duplication." },
  { key: "privilege_log_qc", title: "QC defendant's supplemental privilege log (Vol. 3)", due: 22, who: "paralegal", status: "todo", priority: "low", tags: ["privilege"], source: "manual", age: 4, description: "Check for missing author/recipient fields and categorical descriptions." },
  { key: "hendry_cv", title: "Collect prior testimony and publications for Dr. Hendry", due: 30, who: "paralegal", by: "associate", status: "todo", priority: "low", tags: ["expert", "Daubert"], source: "manual", age: 3, description: "Prior expert reports in platform cases; any testimony on two-sided markets." },
  { key: "client_update", title: "Quarterly update to named plaintiffs", due: 26, who: "owner", status: "todo", priority: "low", tags: ["client"], source: "manual", age: 2, description: "Plain-language status: discovery progress, deposition schedule and class certification timing." },
  { key: "done_rfp2", title: "Serve Plaintiffs' Second Set of RFPs (wallet and NFC access)", due: -12, who: "associate", status: "done", priority: "medium", tags: ["RFP"], source: "manual", age: 300 },
  { key: "done_marsh_digest", title: "Marsh deposition digest and key admissions", due: -9, who: "paralegal", by: "associate", status: "done", priority: "medium", tags: ["deposition"], source: "manual", age: 260 },
  // Tracked government action
  { key: "doj_docket", title: "Docket watch: summarize latest public filings in the government action", due: 1, who: "associate", matter: "doj", status: "todo", priority: "medium", tags: ["docket", "coordination"], source: "docket", age: 22, description: "Summarize new public entries and flag anything that affects deposition sequencing in the consumer case." },
  { key: "doj_coord", title: "Coordination call agenda: shared custodians and deposition sequencing", due: 7, who: "owner", matter: "doj", status: "todo", priority: "medium", tags: ["coordination"], source: "manual", age: 16, description: "Custodian overlap list, cross-notice protocol, and time allocation per witness." },
];

export function buildDemoTasks(ctx: DemoBuildContext): Task[] {
  const person = { owner: ctx.ownerId, associate: A, paralegal: P };
  return TASKS.map((t) => {
    const { key, due, who, by, matter, age, ...rest } = t;
    const createdAt = hoursAgo(ctx.now, age);
    return {
      ...rest,
      id: `${DEMO_ID_PREFIX}task_${key}`,
      matterId: matter === "doj" ? J : C,
      assigneeId: person[who],
      createdById: by ? person[by] : undefined,
      dueAt: dayOffset(ctx.now, due),
      createdAt,
      updatedAt: rest.status === "todo" ? createdAt : hoursAgo(ctx.now, Math.max(1, Math.floor(age / 3))),
    };
  });
}

const WITNESS_BY_DEPOSITION: Record<string, string> = {
  [DEMO_DEPOSITIONS.appStorePolicy]: DEMO_CUSTODIANS.appStorePolicy,
  [DEMO_DEPOSITIONS.paymentsFinance]: DEMO_CUSTODIANS.paymentsFinance,
  [DEMO_DEPOSITIONS.wearables]: DEMO_CUSTODIANS.wearables,
};

/**
 * Calendar events. Depositions already taken use the transcript's own date (so the calendar and the transcript
 * agree); upcoming depositions, conferences and deadlines are relative to the load time.
 */
export function buildDemoEvents(ctx: DemoBuildContext, depositions: Pick<Deposition, "id" | "witnessId" | "witnessName" | "date" | "location">[] = []): CalendarEvent[] {
  const team = [ctx.ownerId, A, P];
  const day = (n: number) => businessDay(ctx.now, n);
  const ev = (e: Omit<CalendarEvent, "id" | "matterId"> & { key: string; matterId?: string }): CalendarEvent => {
    const { key, ...rest } = e;
    return { matterId: C, ...rest, id: `${DEMO_ID_PREFIX}ev_${key}` };
  };
  const taken: CalendarEvent[] = [];
  const takenWitnesses = new Set<string>();
  for (const d of depositions) {
    const witness = d.witnessId || WITNESS_BY_DEPOSITION[d.id];
    takenWitnesses.add(witness);
    const dayOf = d.date.slice(0, 10);
    taken.push(ev({ key: `depo_${d.id}`, title: `Deposition of ${d.witnessName || DEMO_CUSTODIAN_NAMES[witness] || "witness"}`, startsAt: at(dayOf, "09:30"), endsAt: at(dayOf, "17:00"), kind: "deposition", location: d.location ?? "Remote (videoconference)", attendeeIds: [...team, witness, DEMO_OPPOSING_COUNSEL], notes: "Transcript in E-discovery → Depositions.", ruleSource: "FRCP 30(d)(1) — 7 hours on the record" }));
  }
  const upcoming: CalendarEvent[] = [
    ev({ key: "depo_ames", title: "Deposition of Victor Ames (Developer Relations)", startsAt: at(day(9), "09:30"), endsAt: at(day(9), "17:00"), kind: "deposition", location: "Firm office — Conference Room 12A (videographer on site)", attendeeIds: [ctx.ownerId, A, P, DEMO_CUSTODIANS.developerRelations, DEMO_OPPOSING_COUNSEL], notes: "Taking. Link-out entitlement outreach, super-app review notes, cloud-gaming catalog rule.", ruleSource: "FRCP 30" }),
    ev({ key: "depo_reyes", title: "Deposition of Tomas Reyes (Wallet & NFC)", startsAt: at(day(16), "09:00"), endsAt: at(day(16), "16:30"), kind: "deposition", location: "Remote (videoconference)", attendeeIds: [ctx.ownerId, A, DEMO_CUSTODIANS.walletNfc, DEMO_OPPOSING_COUNSEL], notes: "Taking. Tap-to-pay access, NFC controller restrictions, wallet fees. Outline in the Deposition Prep folder.", ruleSource: "FRCP 30" }),
    ev({ key: "depo_nand", title: "Deposition of Priya Nand (Messaging)", startsAt: at(day(23), "09:30"), endsAt: at(day(23), "17:00"), kind: "deposition", location: "Firm office — Conference Room 12A", attendeeIds: [A, P, DEMO_CUSTODIANS.messaging, DEMO_OPPOSING_COUNSEL], notes: "Taking. Cross-platform messaging decisions; coordinate with the government action's notice.", ruleSource: "FRCP 30" }),
    ev({ key: "depo_30b6", title: "Rule 30(b)(6) deposition of defendant (commission structure)", startsAt: at(day(34), "09:00"), endsAt: at(day(34), "17:00"), kind: "deposition", location: "Firm office — Conference Room 12A", attendeeIds: [ctx.ownerId, A, P, DEMO_OPPOSING_COUNSEL], notes: "Topics 1–4 (commission tiers, anti-steering enforcement). Designee not yet identified.", ruleSource: "FRCP 30(b)(6)" }),
    ev({ key: "meet_confer_esi", title: "Meet-and-confer: search terms and structured data", startsAt: at(day(2), "14:00"), endsAt: at(day(2), "15:00"), kind: "meeting", location: "Videoconference", attendeeIds: [A, P, DEMO_OPPOSING_COUNSEL], notes: "Proposed proximity limiters for messaging terms; transaction-level data fields; timing of the payments custodial production." }),
    ev({ key: "meet_confer_priv", title: "Meet-and-confer: privilege log challenges", startsAt: at(day(6), "11:00"), endsAt: at(day(6), "11:45"), kind: "meeting", location: "Videoconference", attendeeIds: [ctx.ownerId, A, DEMO_OPPOSING_COUNSEL], notes: "Thirty-one entries where in-house counsel is only copied on business emails." }),
    ev({ key: "cmc", title: "Further case management conference", startsAt: at(day(13), "10:00"), endsAt: at(day(13), "11:00"), kind: "hearing", location: "San Jose Courthouse, Courtroom 5 (demo)", attendeeIds: [ctx.ownerId, A, DEMO_OPPOSING_COUNSEL], notes: "Joint statement due 7 days before.", ruleSource: "Civil L.R. 16-10" }),
    ev({ key: "cmc_statement_due", title: "Joint case management statement due", startsAt: at(day(6), "17:00"), allDay: true, kind: "filing", attendeeIds: [ctx.ownerId, A], ruleSource: "Civil L.R. 16-10(d)" }),
    ev({ key: "production_deadline", title: "Substantial completion of document production", startsAt: at(dayOffset(ctx.now, 24), "17:00"), allDay: true, kind: "deadline", attendeeIds: team, notes: "Per the scheduling order (demo)." }),
    ev({ key: "class_cert_due", title: "Plaintiffs' class certification motion and expert reports due", startsAt: at(dayOffset(ctx.now, 52), "17:00"), allDay: true, kind: "deadline", attendeeIds: team, ruleSource: "Fed. R. Civ. P. 23; scheduling order (demo)" }),
    ev({ key: "expert_disclosure", title: "Plaintiffs' expert disclosures (Dr. Varga)", startsAt: at(dayOffset(ctx.now, 52), "17:00"), allDay: true, kind: "deadline", attendeeIds: [ctx.ownerId, A], ruleSource: "Fed. R. Civ. P. 26(a)(2)" }),
    ev({ key: "varga_session", title: "Working session with Dr. Varga: overcharge regression", startsAt: at(day(4), "13:00"), endsAt: at(day(4), "15:00"), kind: "meeting", location: "Videoconference", attendeeIds: [ctx.ownerId, A, DEMO_EXPERTS.economist], notes: "Walk through the but-for commission benchmark and pass-through estimates." }),
    ev({ key: "team_standup", title: "Apple team weekly: discovery status", startsAt: at(day(1), "09:00"), endsAt: at(day(1), "09:30"), kind: "internal", location: "Conference Room 9", attendeeIds: team }),
    ev({ key: "hendry_depo", title: "Deposition of Dr. Paul Hendry (defense economist)", startsAt: at(day(128), "09:30"), endsAt: at(day(128), "17:00"), kind: "deposition", location: "Firm office", attendeeIds: [ctx.ownerId, A, DEMO_EXPERTS.defenseEconomist, DEMO_OPPOSING_COUNSEL], ruleSource: "Fed. R. Civ. P. 26(b)(4)(A)" }),
    ev({ key: "doj_coord", matterId: J, title: "Coordination call: consumer class and government action", startsAt: at(day(8), "16:00"), endsAt: at(day(8), "16:45"), kind: "meeting", location: "Videoconference", attendeeIds: [ctx.ownerId, A], notes: "Shared custodians and deposition sequencing (tracked matter)." }),
  ];
  // Fall back to past-dated events for the three transcribed witnesses when the e-discovery pack supplied none.
  const fallback: CalendarEvent[] = [];
  const pastSpecs: [string, string, number][] = [[DEMO_DEPOSITIONS.appStorePolicy, DEMO_CUSTODIANS.appStorePolicy, -41], [DEMO_DEPOSITIONS.paymentsFinance, DEMO_CUSTODIANS.paymentsFinance, -19], [DEMO_DEPOSITIONS.wearables, DEMO_CUSTODIANS.wearables, -6]];
  for (const [depId, witness, offset] of pastSpecs) {
    if (takenWitnesses.has(witness)) continue;
    const dd = day(offset);
    fallback.push(ev({ key: `depo_${depId}`, title: `Deposition of ${DEMO_CUSTODIAN_NAMES[witness]}`, startsAt: at(dd, "09:30"), endsAt: at(dd, "17:00"), kind: "deposition", location: "Remote (videoconference)", attendeeIds: [...team, witness, DEMO_OPPOSING_COUNSEL], ruleSource: "FRCP 30(d)(1)" }));
  }
  return [...taken, ...fallback, ...upcoming];
}

export function buildDemoUpdates(ctx: DemoBuildContext): TeamUpdate[] {
  const u = (key: string, authorId: string, hours: number, kind: TeamUpdate["kind"], body: string, extra: Partial<TeamUpdate> = {}): TeamUpdate => ({ id: `${DEMO_ID_PREFIX}upd_${key}`, authorId, body, matterId: C, createdAt: hoursAgo(ctx.now, hours), kind, ...extra });
  return [
    u("reyes_outline", A, 3, "update", "Reyes outline (PDF) is in Deposition Prep. The exhibit list is pulled from the Wallet & NFC documents in the production. Partner review before Friday?", { attachments: [{ label: "Deposition Prep folder", href: lib }], reactions: { "👍": 2 } }),
    u("okoro_hot", P, 20, "update", "Second-level review of the Okoro payments set is 60% done. Nine new hot documents, mostly pass-through and Small Business Program analyses. Tagged for the class-cert team.", { attachments: [{ label: "Review queue", href: ed() }] }),
    u("marsh_conflict", A, 30, "question", "Marsh qualified her 18:4 answer on the purpose of the anti-steering rule at 97:3, after a break with counsel. Both passages are flagged in the transcript, and Marsh-3 and the Marsh-4 draft (para. 3) support the original answer. Do we take it up with Ames or hold it for trial?", { attachments: [{ label: "Conflicts", href: ed("conflicts") }] }),
    u("damages_model", ctx.ownerId, 52, "update", "Damages workbook v1 is up (overcharge × volume by year). Inputs are placeholders until Dr. Varga's regression is final; the formulas and pass-through sensitivity are wired.", { attachments: [{ label: "Matter folder", href: lib }] }),
    u("ruling_win", ctx.ownerId, 96, "win", "Defense agreed to add the two messaging custodians without motion practice. Thanks, Nina, for the hit-report analysis that got us there.", { reactions: { "🎉": 3, "👏": 2 } }),
    u("doj_note", A, 140, "announcement", "Coordination call with the government action is on the calendar. Please send custodian-overlap questions by Wednesday.", { matterId: J }),
  ];
}
