/**
 * Demo library content for the consumer matter: the matter folder, six working subfolders and notes, memos,
 * clauses and links with real text. Items are synthetic work product (marked "Demo" in their tags).
 */
import type { LibraryItem } from "@/lib/types/domain";
import { LIBRARY_FOLDERS, matterFolderId } from "@/modules/library/ids";
import { DEMO_ID_PREFIX, DEMO_MATTERS, DEMO_TEAM } from "../ids";
import type { DemoBuildContext } from "./context";
import type { DemoMatter } from "./matters";

export const DEMO_FOLDERS = {
  pleadings: `${DEMO_ID_PREFIX}lib_pleadings`,
  discovery: `${DEMO_ID_PREFIX}lib_discovery`,
  correspondence: `${DEMO_ID_PREFIX}lib_correspondence`,
  research: `${DEMO_ID_PREFIX}lib_research`,
  experts: `${DEMO_ID_PREFIX}lib_experts`,
  depoPrep: `${DEMO_ID_PREFIX}lib_depo_prep`,
} as const;

const FOLDER_DEFS: { id: string; name: string; description: string }[] = [
  { id: DEMO_FOLDERS.pleadings, name: "Pleadings", description: "Complaint summaries, answer analysis and the case schedule." },
  { id: DEMO_FOLDERS.discovery, name: "Discovery Requests & Responses", description: "RFPs, interrogatories, responses, ESI protocol and search terms." },
  { id: DEMO_FOLDERS.correspondence, name: "Correspondence", description: "Meet-and-confer letters and notes with defendant's counsel." },
  { id: DEMO_FOLDERS.research, name: "Research", description: "Memos and authority on market definition, anti-steering and class certification." },
  { id: DEMO_FOLDERS.experts, name: "Experts", description: "Expert retention, data requests, damages model and report drafts." },
  { id: DEMO_FOLDERS.depoPrep, name: "Deposition Prep", description: "Outlines, exhibit lists and digests for fact witnesses." },
];

/** Matter folders for both demo matters (same ids the library would create), plus the consumer matter's subfolders. */
export function buildDemoFolders(ctx: DemoBuildContext, matters: DemoMatter[]): LibraryItem[] {
  const at = ctx.now.toISOString();
  const roots: LibraryItem[] = matters.map((m) => ({ id: matterFolderId(m.id), parentId: LIBRARY_FOLDERS.matters, name: m.shortName, type: "folder", matterId: m.id, description: `${m.name}${m.caption ? ` — ${m.caption}` : ""}`, practiceArea: m.practiceArea, ownerId: ctx.ownerId, sharedWith: ["matter-team"], tags: ["demo"], createdAt: at, updatedAt: at }));
  const subs: LibraryItem[] = FOLDER_DEFS.map((f) => ({ id: f.id, parentId: matterFolderId(DEMO_MATTERS.consumer), name: f.name, type: "folder", matterId: DEMO_MATTERS.consumer, description: f.description, practiceArea: "Litigation", ownerId: ctx.ownerId, sharedWith: ["matter-team"], tags: ["demo"], createdAt: at, updatedAt: at }));
  return [...roots, ...subs];
}

interface ItemSpec { key: string; folder: keyof typeof DEMO_FOLDERS; name: string; type: "note" | "clause" | "link"; content?: string; url?: string; description?: string; tags?: string[]; owner?: "owner" | "associate" | "paralegal"; starred?: boolean; daysAgo: number; status?: LibraryItem["status"] }

const ITEMS: ItemSpec[] = [
  // Pleadings
  { key: "complaint_summary", folder: "pleadings", type: "note", name: "Consolidated complaint — claim-by-claim summary", daysAgo: 400, owner: "associate", starred: true, tags: ["complaint", "summary"], content: `# Consolidated class action complaint — summary (demo)\n\n**Claims.** Count I: monopolization of the U.S. performance-smartphone market (Sherman Act § 2). Count II: attempted monopolization. Count III: monopolization of the iOS app-distribution market. Count IV: state consumer-protection claims (pleaded in the alternative).\n\n**Theory.** Defendant maintained monopoly power by (1) requiring all native app distribution through its store; (2) anti-steering rules preventing developers from telling users about cheaper payment options; (3) restricting super apps and cloud game streaming; (4) degrading cross-platform messaging; (5) limiting third-party smartwatch functionality; and (6) blocking third-party tap-to-pay wallets from NFC access.\n\n**Injury.** App Store purchasers paid supra-competitive commissions passed through in app prices; iPhone purchasers paid higher device prices due to switching costs.\n\n**Class.** All U.S. persons who purchased an iPhone or paid for apps or in-app content through the App Store during the class period.\n\n_All internal facts in this demo matter are synthetic._` },
  { key: "answer_defenses", folder: "pleadings", type: "note", name: "Answer — affirmative defenses to address", daysAgo: 300, owner: "associate", tags: ["answer", "defenses"], content: `# Answer: affirmative defenses (demo)\n\n1. **Procompetitive justifications** — security, privacy, and platform integrity. Plan: test through the Marsh and Nand testimony whether the stated justifications were the actual contemporaneous reasons.\n2. **Illinois Brick / direct purchaser** — defendant contends app purchasers are not direct purchasers of distribution services. Plan: brief with the class certification motion.\n3. **Statute of limitations** — four-year period under 15 U.S.C. § 15b; continuing-violation argument for rule revisions.\n4. **Failure to mitigate** — weak; note only.\n5. **Arbitration / class waiver** — none applicable to App Store purchasers per the current terms (confirm version history).` },
  { key: "schedule", folder: "pleadings", type: "note", name: "Case schedule and deadlines (working copy)", daysAgo: 20, owner: "paralegal", starred: true, tags: ["schedule"], content: `# Case schedule (demo)\n\n| Event | Deadline |\n|---|---|\n| Substantial completion of production | +24 days from load |\n| Class certification motion + expert reports | +52 days |\n| Close of fact discovery | +95 days |\n| Opposition to class certification | +110 days |\n| Class certification hearing | +150 days |\n\nThe live dates are on the matter calendar; this note is a working copy for the team.` },
  // Discovery
  { key: "esi_protocol", folder: "discovery", type: "note", name: "ESI protocol — key terms", daysAgo: 350, owner: "paralegal", tags: ["ESI", "protocol"], content: `# ESI protocol: key terms (demo)\n\n- **Format:** single-page TIFF with extracted text and load files; spreadsheets, presentations and structured data produced natively.\n- **Metadata fields:** BegBates, EndBates, Custodian, AllCustodians, From, To, CC, BCC, Subject, DateSent, FileName, MD5, FamilyID.\n- **Deduplication:** global, with AllCustodians populated.\n- **Threading:** email threading permitted; lesser-included emails logged.\n- **Privilege log:** within 30 days of each production; metadata log acceptable for communications solely among counsel.\n- **Bates prefix:** APL-DEMO for defendant's production.` },
  { key: "search_terms", folder: "discovery", type: "note", name: "Search terms — negotiated list with hit counts", daysAgo: 6, owner: "associate", tags: ["search terms", "ESI"], content: `# Search terms (demo)\n\n| # | Term | Status | Unique hits |\n|---|---|---|---|\n| 1 | (anti-steer* OR "reader rule" OR "link out") | Agreed | 18,420 |\n| 2 | (commission w/5 (rate OR tier OR "small business")) | Agreed | 22,915 |\n| 3 | ("super app" OR "mini app" OR "mini-program") | Agreed | 6,302 |\n| 4 | ("cloud gam*" OR "game streaming") w/10 (review OR catalog) | Agreed | 4,118 |\n| 5 | ("green bubble" OR "iMessage for Android") | Disputed — proposed proximity limiter | 41,077 |\n| 6 | (NFC w/5 (access OR "third party" OR wallet)) | Agreed | 9,640 |\n| 7 | (smartwatch OR "third-party watch") w/10 (API OR notification) | Agreed | 5,205 |` },
  { key: "rog_responses", folder: "discovery", type: "note", name: "Defendant's responses to Interrogatories 1–12 — deficiencies", daysAgo: 45, owner: "associate", tags: ["interrogatories", "deficiency"], content: `# Interrogatory responses: deficiencies (demo)\n\n- **No. 3 (persons with knowledge of commission-rate decisions):** lists titles only; demand names.\n- **No. 5 (revenue attributable to link-out restrictions):** objects as calling for expert opinion; it asks for data the company tracks. Demand the underlying reports.\n- **No. 8 (security justification for NFC restrictions):** narrative answer with no documents identified under Rule 33(d).\n- **No. 11 (policy revisions since 2019):** incomplete; omits the 2018 revisions to the anti-steering rationale memo reflected in produced drafts.` },
  { key: "rfp_def_clause", folder: "discovery", type: "clause", name: "Definition — \"Anti-Steering Rules\" (RFP definitions)", daysAgo: 380, owner: "associate", tags: ["definition", "RFP"], content: `"Anti-Steering Rules" means any guideline, policy, contractual term, review practice or enforcement action, in any version, that restricts or conditions the ability of a developer to communicate with users about, link to, or offer purchasing mechanisms for digital goods or services other than Your in-app purchase system, including any "reader app" or link-out entitlement and any commission applicable to purchases made through such links.` },
  { key: "rfp_instr_clause", folder: "discovery", type: "clause", name: "Instruction — structured transaction data", daysAgo: 380, owner: "associate", tags: ["instruction", "structured data"], content: `Produce transaction-level data for all App Store purchases by U.S. accounts during the Relevant Period in native, machine-readable form, including for each transaction: anonymized account identifier, transaction date, storefront, developer identifier, app identifier, product type (paid download, in-app purchase, subscription), price paid, currency, commission rate applied, commission amount, and any refund or chargeback, together with a data dictionary sufficient to interpret every field.` },
  // Correspondence
  { key: "mc_letter_0915", folder: "correspondence", type: "note", name: "Letter to defense counsel — custodian date ranges", daysAgo: 12, owner: "associate", tags: ["meet-and-confer", "letter"], content: `Dear Counsel:\n\nWe write regarding the date ranges for the App Store Policy and Developer Relations custodians. Your letter proposes collecting from January 2021 forward. The anti-steering conduct at issue dates to at least 2016, and your own production contains 2016–2018 policy correspondence and drafts of the anti-steering rationale memo. A January 2016 start date is proportional to the needs of the case.\n\nWe are prepared to phase the collection — Marsh and Ames first — and to meet and confer this week.\n\nVery truly yours,\n\n[Demo correspondence; fictional counsel]` },
  { key: "mc_notes", folder: "correspondence", type: "note", name: "Meet-and-confer notes — structured data", daysAgo: 5, owner: "paralegal", tags: ["meet-and-confer", "notes"], content: `# Meet-and-confer notes: structured data (demo)\n\n**Attendees:** our team (3); defense counsel Colin Mercer and Serena Holt (Hartwell & Pryor LLP, fictional) and two associates.\n\n- Defense will produce a 1% sample of transaction data with a data dictionary within two weeks.\n- Refunds and chargebacks: defense says stored in a separate system; will confirm fields.\n- Commission-rate field: present only from 2021; earlier years require derivation from tier tables (we asked for the tables).\n- Next step: joint letter brief if the full dataset is not agreed by the next conference.` },
  { key: "cocounsel_email", folder: "correspondence", type: "note", name: "Coordination note — government action discovery overlap", daysAgo: 16, owner: "owner", tags: ["coordination"], content: `# Coordination with the tracked government action (demo)\n\n- Overlapping custodians identified from public filings and our production: messaging and wallet leads.\n- Cross-notice protocol to be proposed so a witness is deposed once where possible, with time split by agreement.\n- No confidential material from either case is shared outside the protective orders.` },
  // Research
  { key: "market_def_note", folder: "research", type: "note", name: "Market definition — smartphone vs. performance smartphone", daysAgo: 40, owner: "associate", starred: true, tags: ["market definition", "research"], content: `# Market definition (demo research note)\n\n**Question.** Should the class plead and prove a U.S. smartphone market or a narrower performance-smartphone market?\n\n**Considerations.**\n- Hypothetical monopolist test: switching costs (data, app purchases, messaging lock-in) support a narrower market.\n- Price discrimination between premium and entry-level devices supports a performance-smartphone submarket.\n- Two-sided platform analysis: app-distribution claims may require considering both developer and consumer sides (see Ohio v. American Express Co., 585 U.S. 529 (2018)).\n\n**Recommendation.** Plead both; have Dr. Varga test the narrower market with the transaction data. [VERIFY citations before filing.]` },
  { key: "anti_steering_note", folder: "research", type: "note", name: "Anti-steering — prior litigation and remedies (public record)", daysAgo: 35, owner: "associate", tags: ["anti-steering", "research"], content: `# Anti-steering: public-record background (demo research note)\n\n- Prior developer litigation challenged app-store anti-steering rules under state unfair-competition law and resulted in an injunction addressing link-out restrictions (see Epic Games, Inc. v. Apple Inc., 67 F.4th 946 (9th Cir. 2023)).\n- Compliance with that injunction has itself been litigated; follow the public docket for the scope of permitted link-outs and commissions.\n- Relevance here: whether anti-steering rules raised consumer prices (pass-through) and whether the class can show common impact.\n\n[VERIFY: pin cites and subsequent history before use in any filing.]` },
  { key: "class_cert_auth", folder: "research", type: "note", name: "Class certification — common impact authorities", daysAgo: 22, owner: "associate", tags: ["class certification"], content: `# Common impact (demo research note)\n\n- Comcast Corp. v. Behrend, 569 U.S. 27 (2013): damages model must measure damages attributable to the theory of liability.\n- Olean Wholesale Grocery Coop. v. Bumble Bee Foods LLC, 31 F.4th 651 (9th Cir. 2022) (en banc): plaintiffs must prove Rule 23 prerequisites by a preponderance; presence of some uninjured members does not automatically defeat predominance.\n- Tyson Foods, Inc. v. Bouaphakeo, 577 U.S. 442 (2016): representative evidence may establish classwide liability where each member could rely on it individually.\n\n[VERIFY before filing.]` },
  { key: "sherman_link", folder: "research", type: "link", name: "15 U.S.C. § 2 — Monopolizing trade (statute text)", url: "https://www.law.cornell.edu/uscode/text/15/2", daysAgo: 400, owner: "associate", tags: ["statute"] },
  { key: "clayton4_link", folder: "research", type: "link", name: "15 U.S.C. § 15 — Suits by persons injured (Clayton Act § 4)", url: "https://www.law.cornell.edu/uscode/text/15/15", daysAgo: 400, owner: "associate", tags: ["statute", "damages"] },
  { key: "frcp23_link", folder: "research", type: "link", name: "Fed. R. Civ. P. 23 — Class actions", url: "https://www.law.cornell.edu/rules/frcp/rule_23", daysAgo: 300, owner: "paralegal", tags: ["rules", "class certification"] },
  // Experts
  { key: "varga_retention", folder: "experts", type: "note", name: "Dr. Varga — retention scope and data requests", daysAgo: 90, owner: "owner", tags: ["expert", "retention"], content: `# Dr. Elise Varga (fictional) — scope (demo)\n\n**Scope.** Market definition, monopoly power, but-for commission benchmark, overcharge and pass-through to consumers, classwide damages.\n\n**Data requested.** Transaction-level App Store data; commission tier tables by year; developer price-change histories after commission changes; device price and switching-survey data.\n\n**Protective order.** Exhibit A acknowledgment signed; data stays on the expert's secured environment.` },
  { key: "damages_method", folder: "experts", type: "note", name: "Damages methodology — overcharge × volume (working note)", daysAgo: 14, owner: "associate", tags: ["damages", "methodology"], content: `# Damages methodology (demo working note)\n\nDamages by year = (actual effective commission − but-for commission) × consumer-facing App Store billings × pass-through rate.\n\n- **But-for commission:** benchmark from competitive distribution channels (to be supported by the expert).\n- **Pass-through:** estimated from developer price responses to commission changes.\n- **Volume:** U.S. consumer billings from produced transaction data.\n\nThe damages workbook in this folder implements the formula with placeholder inputs; every figure is synthetic until the expert's analysis is final.` },
  { key: "hendry_notes", folder: "experts", type: "note", name: "Dr. Hendry (defense) — anticipated rebuttal themes", daysAgo: 9, owner: "associate", tags: ["expert", "rebuttal"], content: `# Anticipated defense economist themes (demo)\n\n1. Two-sided market: any commission effect on developers is offset by consumer-side benefits.\n2. Pass-through near zero for free-to-download apps monetized by in-app purchases.\n3. Heterogeneity across developers defeats common impact.\n4. The but-for commission benchmark is not comparable (different services bundled).\n\nPrepare Dr. Varga to address each in reply.` },
  // Deposition prep
  { key: "marsh_digest", folder: "depoPrep", type: "note", name: "Marsh deposition — digest and key admissions", daysAgo: 9, owner: "paralegal", tags: ["deposition", "digest"], content: `# Lena Marsh (Director, App Store Policy; fictional) — digest (demo)\n\n- **18:4** — Agreed the purpose of the anti-steering provision was to keep the purchase in the app. **Qualified at 97:3** after a break with counsel: the "main purpose" was user trust; protecting the commission is "an effect". Cite both passages together.\n- **22:5** — On Exhibit Marsh-3 (9 May 2017): a visible web price means many users would buy outside the app.\n- **22:18** — Told Developer Relations "Don't get into why"; explanations "get quoted back to us" (flagged evasive).\n- **31:5** — Wrote in the first draft of the rationale memo (Marsh-4, para. 3) that the main effect of enforcement is to protect the commission; revised after comments.\n\nFull transcript with page/line cites: E-discovery → Depositions.` },
  { key: "exhibit_list", folder: "depoPrep", type: "note", name: "Master exhibit list — fact depositions", daysAgo: 4, owner: "paralegal", tags: ["exhibits"], content: `# Master exhibit list (demo)\n\n| Exh. | Description | Witness |\n|---|---|---|\n| Marsh-3 | Marsh reply, "RE: FW: Kitebird — request to show web pricing in app" (9 May 2017) | Marsh |\n| Marsh-4 | Draft v1 of the anti-steering rationale memo (17 Jul 2018) | Marsh |\n| Okoro-9 | "Commission pass-through: price-tier analysis" (3 Mar 2020) | Okoro |\n| Okoro-10 | "Small Business Program — revenue impact scenarios" deck (28 Sep 2020) | Okoro |\n| Frey-3 | Morita reply, "policy, not physics" (16 Mar 2017) | Frey |\n| Frey-7 | "Wearables ecosystem strategy — attach and retention" deck (Aug. 2019) | Frey |\n\nEach exhibit's Bates number is on the transcript's exhibit list in E-discovery → Depositions; confirm against the production index before re-marking.` },
  { key: "depo_protocol_clause", folder: "depoPrep", type: "clause", name: "Remote deposition protocol — exhibit sharing paragraph", daysAgo: 200, owner: "associate", tags: ["protocol", "remote deposition"], content: `Exhibits shall be shared through the court reporter's electronic exhibit platform. The examining attorney shall introduce each exhibit by Bates number; the witness and defending counsel shall be given control to scroll the complete exhibit. Exhibits designated Highly Confidential under the Protective Order shall be shown only after persons not authorized to view them have left the virtual room, and the transcript shall be designated accordingly.` },
];

export function buildDemoLibraryItems(ctx: DemoBuildContext): LibraryItem[] {
  const person = { owner: ctx.ownerId, associate: DEMO_TEAM.associate, paralegal: DEMO_TEAM.paralegal };
  return ITEMS.map((it) => {
    const createdAt = new Date(ctx.now.getTime() - it.daysAgo * 86_400_000).toISOString();
    return {
      id: `${DEMO_ID_PREFIX}lib_${it.key}`,
      parentId: DEMO_FOLDERS[it.folder],
      name: it.name,
      type: it.type,
      matterId: DEMO_MATTERS.consumer,
      description: it.description,
      content: it.content,
      url: it.url,
      size: it.content?.length,
      tags: ["demo", ...(it.tags ?? [])],
      ownerId: person[it.owner ?? "associate"],
      sharedWith: ["matter-team"],
      practiceArea: "Litigation",
      starred: it.starred,
      status: it.status ?? (it.type === "clause" ? "approved" : "draft"),
      version: 1,
      createdAt,
      updatedAt: createdAt,
    } satisfies LibraryItem;
  });
}
