import "server-only";
import type { Database } from "@/lib/db";
import type { Matter, Person } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "./ids";

const people: Person[] = [
  { id: PEOPLE.jordanWhitfield, name: "Jordan Whitfield", email: "jwhitfield@seegerweiss.com", title: "Partner", organization: "Seeger Weiss LLP", role: "attorney", tags: ["litigation", "MDL"] },
  { id: PEOPLE.priyaRaman, name: "Priya Raman", email: "praman@seegerweiss.com", title: "Partner", organization: "Seeger Weiss LLP", role: "attorney", tags: ["products liability", "toxic tort"] },
  { id: PEOPLE.danielOkafor, name: "Daniel Okafor", email: "dokafor@seegerweiss.com", title: "Senior Associate", organization: "Seeger Weiss LLP", role: "attorney", tags: ["commercial", "M&A"] },
  { id: PEOPLE.elenaMarsh, name: "Elena Marsh", email: "emarsh@seegerweiss.com", title: "Associate", organization: "Seeger Weiss LLP", role: "attorney", tags: ["litigation"] },
  { id: PEOPLE.samuelChen, name: "Samuel Chen", email: "schen@seegerweiss.com", title: "Associate", organization: "Seeger Weiss LLP", role: "attorney", tags: ["employment", "regulatory"] },
  { id: PEOPLE.mariaLopez, name: "Maria Lopez", email: "mlopez@seegerweiss.com", title: "Litigation Paralegal", organization: "Seeger Weiss LLP", role: "paralegal" },
  { id: PEOPLE.tomBradley, name: "Tom Bradley", email: "tbradley@seegerweiss.com", title: "E-Discovery Project Manager", organization: "Seeger Weiss LLP", role: "staff" },
  { id: PEOPLE.aishaKhan, name: "Aisha Khan", email: "akhan@seegerweiss.com", title: "Knowledge Management Director", organization: "Seeger Weiss LLP", role: "staff" },
  { id: PEOPLE.gregoryHale, name: "Gregory Hale", email: "g.hale@meridianfluorochem.com", title: "Director, Environmental Health & Safety", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.helenVoss, name: "Helen Voss", email: "h.voss@meridianfluorochem.com", title: "Senior Toxicologist", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.nadiaBrooks, name: "Nadia Brooks", email: "n.brooks@meridianfluorochem.com", title: "Product Stewardship Manager", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.alanPryce, name: "Alan Pryce", email: "a.pryce@meridianfluorochem.com", title: "VP, Fire Suppression Products", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.robertKaine, name: "Robert Kaine", email: "r.kaine@meridianfluorochem.com", title: "Associate General Counsel", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.martinSuarez, name: "Martin Suarez", email: "m.suarez@meridianfluorochem.com", title: "Regulatory Affairs Counsel", organization: "Meridian Fluorochem Corp.", role: "custodian" },
  { id: PEOPLE.drLindaWhitfieldTox, name: "Dr. Linda Whitfield", title: "Toxicologist (Whitfield Laboratories)", organization: "Whitfield Laboratories", role: "expert" },
  { id: PEOPLE.drRajPatelHydro, name: "Dr. Raj Patel", title: "Hydrogeologist", organization: "Patel Groundwater Sciences", role: "expert" },
  { id: PEOPLE.opposingCounselKlein, name: "Rebecca Klein", title: "Plaintiffs' Executive Committee", organization: "Klein & Associates", role: "opposing" },
  { id: PEOPLE.judgeGergel, name: "Hon. Richard M. Gergel", title: "U.S. District Judge", organization: "D.S.C.", role: "judge" },
];

const matters: Matter[] = [
  {
    id: MATTERS.afff,
    slug: "afff-pfas-mdl-2873",
    name: "In re: Aqueous Film-Forming Foams Products Liability Litigation",
    shortName: "AFFF / PFAS",
    caption: "MDL No. 2873 (D.S.C.)",
    client: "Meridian Fluorochem Corp.",
    clientSide: "defendant",
    practiceArea: "Products Liability",
    court: "U.S. District Court for the District of South Carolina",
    jurisdiction: "Federal · 4th Cir.",
    judge: "Hon. Richard M. Gergel",
    status: "active",
    stage: "Tier 2 custodial review · expert discovery",
    openedAt: "2023-02-14",
    teamIds: [PEOPLE.jordanWhitfield, PEOPLE.priyaRaman, PEOPLE.elenaMarsh, PEOPLE.mariaLopez, PEOPLE.tomBradley],
    leadAttorneyId: PEOPLE.jordanWhitfield,
    description: "Defense of Meridian Fluorochem in the AFFF multidistrict litigation. Personal injury and water-provider claims arising from PFOA/PFOS in firefighting foam. Current focus: custodial document production, TSCA §8(e) knowledge timeline, and rebuttal of plaintiffs' toxicology and hydrogeology experts.",
    keyDates: [
      { label: "Tier 2 production deadline", date: "2026-10-14" },
      { label: "Rebuttal expert reports due", date: "2026-11-06" },
      { label: "Daubert motions", date: "2026-12-18" },
      { label: "Bellwether trial (Group C)", date: "2027-03-08" },
    ],
    tags: ["MDL", "PFAS", "toxic tort", "bellwether"],
  },
  {
    id: MATTERS.depo,
    slug: "depo-provera-mdl-3140",
    name: "In re: Depo-Provera (Depot Medroxyprogesterone Acetate) Products Liability Litigation",
    shortName: "Depo-Provera",
    caption: "MDL No. 3140 (N.D. Fla.)",
    client: "Confidential pharmaceutical distributor",
    clientSide: "defendant",
    practiceArea: "Products Liability",
    court: "U.S. District Court for the Northern District of Florida",
    jurisdiction: "Federal · 11th Cir.",
    judge: "Hon. M. Casey Rodgers",
    status: "active",
    stage: "Pleadings · science day preparation",
    openedAt: "2025-03-03",
    teamIds: [PEOPLE.priyaRaman, PEOPLE.samuelChen, PEOPLE.mariaLopez],
    leadAttorneyId: PEOPLE.priyaRaman,
    description: "Meningioma failure-to-warn claims. Monitoring master complaint, preemption strategy, and epidemiology literature (Roland et al. 2024, BMJ).",
    keyDates: [
      { label: "Master answer due", date: "2026-10-02" },
      { label: "Science Day", date: "2026-11-20" },
    ],
    tags: ["MDL", "pharma", "failure to warn", "preemption"],
  },
  {
    id: MATTERS.northgate,
    slug: "northgate-v-apex",
    name: "Northgate Logistics, Inc. v. Apex Freight Systems, LLC",
    shortName: "Northgate v. Apex",
    caption: "No. 1:26-cv-02218 (N.D. Ill.)",
    client: "Northgate Logistics, Inc.",
    clientSide: "plaintiff",
    practiceArea: "Commercial",
    court: "U.S. District Court for the Northern District of Illinois",
    jurisdiction: "Federal · 7th Cir.",
    judge: "Hon. Sara L. Ellis",
    status: "active",
    stage: "Summary judgment briefing",
    openedAt: "2026-01-20",
    teamIds: [PEOPLE.danielOkafor, PEOPLE.elenaMarsh, PEOPLE.mariaLopez],
    leadAttorneyId: PEOPLE.danielOkafor,
    description: "Breach of a master transportation services agreement; indemnity and consequential-damages waiver dispute after cargo losses at the Joliet cross-dock.",
    keyDates: [
      { label: "MSJ opposition due", date: "2026-10-09" },
      { label: "Reply due", date: "2026-10-23" },
      { label: "Final pretrial conference", date: "2027-01-12" },
    ],
    tags: ["contract", "indemnity", "UCC"],
  },
  {
    id: MATTERS.harbor,
    slug: "project-harbor",
    name: "Project Harbor — Acquisition of Bluewater Analytics, Inc.",
    shortName: "Project Harbor",
    client: "Harborline Technologies, Inc.",
    clientSide: "buyer",
    practiceArea: "Corporate / M&A",
    status: "active",
    stage: "Confirmatory diligence · SPA negotiation",
    openedAt: "2026-07-08",
    teamIds: [PEOPLE.danielOkafor, PEOPLE.samuelChen, PEOPLE.aishaKhan],
    leadAttorneyId: PEOPLE.danielOkafor,
    description: "$184M cash-and-stock acquisition. Open items: IP assignment chain for the core ML models, change-of-control consents in top-20 customer contracts, R&W insurance binder.",
    keyDates: [
      { label: "SPA signing target", date: "2026-10-30" },
      { label: "HSR filing", date: "2026-11-06" },
    ],
    tags: ["M&A", "diligence", "SPA"],
  },
  {
    id: MATTERS.sterling,
    slug: "sterling-medical-employment",
    name: "Sterling Medical Group — Wage & Hour Class Investigation",
    shortName: "Sterling Medical",
    client: "Sterling Medical Group, P.C.",
    clientSide: "defendant",
    practiceArea: "Employment",
    court: "Superior Court of California, County of Los Angeles",
    jurisdiction: "California",
    status: "pre-suit",
    stage: "Pre-suit investigation · PAGA notice response",
    openedAt: "2026-08-19",
    teamIds: [PEOPLE.samuelChen, PEOPLE.jordanWhitfield],
    leadAttorneyId: PEOPLE.samuelChen,
    description: "Response to a PAGA notice alleging meal-period and rounding violations across 14 clinics. Payroll data analysis and exposure modeling underway.",
    keyDates: [{ label: "LWDA cure period ends", date: "2026-10-21" }],
    tags: ["PAGA", "wage and hour", "class"],
  },
];

export function seedCore(db: Database) {
  db.people.putMany(people);
  db.matters.putMany(matters);
}
