"use client";
import * as React from "react";
import Link from "next/link";
import { AlertTriangle, Bot, Calculator, CalendarClock, CheckSquare, ChevronDown, ExternalLink, Gavel, KeyRound, ListChecks, Newspaper, RefreshCw, Scale, Sparkles, StickyNote, Users, type LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tip } from "@/components/ui/tooltip";
import type { BriefItem } from "../types";
import { relativeLabel } from "../time";
import { useHome } from "./home-provider";
import { useHomeUI, type HomeSection } from "../store";
import { MatterBadge } from "./shared";

const KIND_ICON: Record<BriefItem["kind"], LucideIcon> = { deadline: CalendarClock, hearing: Gavel, task: CheckSquare, news: Newspaper, update: Users, matter: Scale, note: StickyNote };
const KIND_TONE: Record<BriefItem["kind"], string> = { deadline: "text-destructive", hearing: "text-primary", task: "text-chart-3", news: "text-chart-2", update: "text-chart-4", matter: "text-primary", note: "text-muted-foreground" };

/** Minimal inline markdown: **bold**, `code`, and [text](url). */
function inline(text: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  const re = /(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\([^)]+\))/g;
  let last = 0, i = 0;
  for (const m of text.matchAll(re)) {
    const idx = m.index ?? 0;
    if (idx > last) out.push(text.slice(last, idx));
    const tok = m[0];
    if (tok.startsWith("**")) out.push(<strong key={i++} className="font-semibold text-foreground">{tok.slice(2, -2)}</strong>);
    else if (tok.startsWith("`")) out.push(<code key={i++} className="rounded bg-muted px-1 font-mono text-[11px]">{tok.slice(1, -1)}</code>);
    else { const mm = /\[([^\]]+)\]\(([^)]+)\)/.exec(tok); if (mm) out.push(<a key={i++} href={mm[2]} target="_blank" rel="noreferrer" className="text-primary underline underline-offset-2">{mm[1]}</a>); }
    last = idx + tok.length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

const SECTION_FROM_HASH: Record<string, HomeSection> = { calendar: "calendar", tasks: "tasks", news: "news", updates: "updates", matters: "matters" };

export function DailyBriefCard({ className }: { className?: string }) {
  const { brief, briefLoading, regenerateBrief, aiConfigured, now } = useHome();
  const setFocus = useHomeUI((s) => s.setFocus);
  const [showAll, setShowAll] = React.useState(false);
  const items = showAll ? brief.items : brief.items.slice(0, 7);

  const go = (href?: string | null) => (e: React.MouseEvent) => {
    if (!href) return;
    if (href.startsWith("/#")) {
      e.preventDefault();
      const key = href.slice(2);
      const section = SECTION_FROM_HASH[key];
      setFocus(null);
      requestAnimationFrame(() => document.getElementById(key)?.scrollIntoView({ behavior: "smooth", block: "start" }));
      if (section === "tasks") setFocus(null);
    }
  };

  return (
    <section className={cn("relative flex min-w-0 flex-col overflow-hidden rounded-xl border bg-card shadow-xs", className)} aria-label="Daily brief">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent" />
      <header className="flex h-11 shrink-0 items-center gap-2 border-b px-3.5">
        <Sparkles className="size-4 text-primary" />
        <h2 className="text-[13px] font-semibold tracking-tight">Daily brief</h2>
        {brief.source === "ai" ? (
          <Tip label={`Generated by ${brief.model ?? "OpenAI"} · ${new Date(brief.generatedAt).toLocaleString()}`}><Badge variant="success" className="gap-1"><Bot className="size-3" /> AI</Badge></Tip>
        ) : (
          <Tip label={aiConfigured ? "Computed from your calendar, tasks, news and updates. Click Regenerate for an AI brief." : "No OpenAI key configured. This brief is computed from your data."}><Badge variant="muted" className="gap-1"><Calculator className="size-3" /> Computed</Badge></Tip>
        )}
        <span className="hidden text-[11px] text-muted-foreground sm:inline">Updated {relativeLabel(brief.generatedAt, now)}</span>
        <div className="flex-1" />
        <div className="flex items-center">
          <Button variant="outline" size="xs" className="rounded-r-none" onClick={() => void regenerateBrief("ai")} disabled={briefLoading}>
            <RefreshCw className={cn("size-3", briefLoading && "animate-spin")} /> {briefLoading ? "Generating…" : "Regenerate"}
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild><Button variant="outline" size="xs" className="rounded-l-none border-l-0 px-1.5" aria-label="More brief options" disabled={briefLoading}><ChevronDown className="size-3" /></Button></DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-64">
              <DropdownMenuItem onClick={() => void regenerateBrief("ai")}><Bot /> Regenerate with AI<span className="ml-auto text-[10px] text-muted-foreground">fast model</span></DropdownMenuItem>
              <DropdownMenuItem onClick={() => void regenerateBrief("computed")}><Calculator /> Recompute without AI</DropdownMenuItem>
              <DropdownMenuItem asChild><Link href="/settings#ai"><KeyRound /> AI configuration</Link></DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>

      <div className="flex min-h-0 flex-1 flex-col gap-3 p-3.5">
        {briefLoading ? (
          <div className="space-y-2.5">
            <Skeleton className="h-4 w-3/4" />
            {Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-3.5" style={{ width: `${88 - (i % 3) * 9}%` }} />)}
          </div>
        ) : (
          <>
            <p className="font-serif text-[15px] leading-snug text-foreground text-balance">{brief.headline}</p>
            {!aiConfigured && (
              <div className="flex items-start gap-2 rounded-md border border-warning/40 bg-warning/10 px-2.5 py-1.5 text-[11.5px] text-warning-foreground dark:text-warning">
                <AlertTriangle className="mt-0.5 size-3.5 shrink-0" />
                <span>OpenAI key required for an AI-written brief. Showing a computed brief from deadlines, tasks and updates. <Link href="/settings#ai" className="font-medium underline underline-offset-2">Add key</Link></span>
              </div>
            )}
            <ol className="space-y-1.5">
              {items.map((it, i) => {
                const Icon = KIND_ICON[it.kind] ?? StickyNote;
                const external = it.href && /^https?:/.test(it.href);
                const body = (
                  <li key={i} className="group flex items-start gap-2 rounded-md px-1.5 py-1 -mx-1.5 hover:bg-accent/50 transition-colors animate-slide-up" style={{ animationDelay: `${i * 30}ms` }}>
                    <Icon className={cn("mt-0.5 size-3.5 shrink-0", KIND_TONE[it.kind] ?? "text-muted-foreground")} />
                    <span className="min-w-0 flex-1 text-[13px] leading-snug text-foreground/90">
                      {inline(it.text)}
                      {it.matterId && <MatterBadge matterId={it.matterId} className="ml-1.5 align-middle" />}
                      {external && <ExternalLink className="ml-1 inline size-3 align-middle text-muted-foreground opacity-0 group-hover:opacity-100" />}
                    </span>
                  </li>
                );
                if (!it.href) return body;
                return external ? (
                  <a key={i} href={it.href} target="_blank" rel="noreferrer" className="block">{body}</a>
                ) : (
                  <Link key={i} href={it.href} onClick={go(it.href)} className="block">{body}</Link>
                );
              })}
            </ol>
            {brief.items.length > 7 && (
              <button onClick={() => setShowAll((v) => !v)} className="self-start text-[11.5px] font-medium text-primary hover:underline underline-offset-2 cursor-pointer">{showAll ? "Show fewer" : `Show ${brief.items.length - 7} more`}</button>
            )}
          </>
        )}
      </div>
    </section>
  );
}

/** The four numbers behind the brief; rendered next to the greeting. */
export function BriefStats({ className }: { className?: string }) {
  const { brief } = useHome();
  const setFocus = useHomeUI((s) => s.setFocus);
  const setTaskFilter = useHomeUI((s) => s.setTaskFilter);
  return (
    <div className={cn("grid max-w-md grid-cols-2 gap-1.5", className)}>
      <Stat icon={CalendarClock} label="Today" value={brief.stats.eventsToday} hint={`${brief.stats.eventsThisWeek} this week`} onClick={() => setFocus("calendar")} />
      <Stat icon={AlertTriangle} label="Overdue" value={brief.stats.overdueTasks} tone={brief.stats.overdueTasks ? "text-destructive" : undefined} hint="tasks" onClick={() => { setTaskFilter({ overdue: true }); setFocus("tasks"); }} />
      <Stat icon={ListChecks} label="Due in 7d" value={brief.stats.dueSoonTasks} hint="tasks" onClick={() => { setTaskFilter({ overdue: false }); setFocus("tasks"); }} />
      <Stat icon={Newspaper} label="Hot news" value={brief.stats.hotNews} hint="last 7 days" onClick={() => setFocus("news")} />
    </div>
  );
}

function Stat({ icon: Icon, label, value, hint, tone, onClick }: { icon: LucideIcon; label: string; value: number; hint?: string; tone?: string; onClick?: () => void }) {
  return (
    <button onClick={onClick} className="flex items-center gap-2 rounded-md border bg-card px-2.5 py-2 text-left shadow-xs transition-colors hover:bg-accent/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 cursor-pointer">
      <Icon className={cn("size-4 shrink-0 text-muted-foreground", tone)} />
      <div className="min-w-0 leading-tight">
        <div className={cn("text-base font-semibold tabular", tone)}>{value}</div>
        <div className="truncate text-[10px] uppercase tracking-wider text-muted-foreground">{label}{hint ? ` · ${hint}` : ""}</div>
      </div>
    </button>
  );
}
