import type { Deposition } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "@/lib/seed/ids";
import { KLEIN, WHITFIELD, obj, qa } from "./seed-helpers";

/**
 * Deposition of Alan Pryce, Vice President, Fire Suppression Products,
 * Meridian Fluorochem Corp. Taken by Rebecca Klein; defended by Jordan
 * Whitfield with Priya Raman. Rough transcript, certified copy pending.
 */
export const PRYCE_DEPOSITION: Deposition = {
  id: "dep_afff_pryce_v1",
  matterId: MATTERS.afff,
  witnessId: PEOPLE.alanPryce,
  witnessName: "Alan Pryce",
  witnessTitle: "Vice President, Fire Suppression Products, Meridian Fluorochem Corp.",
  date: "2026-07-22",
  takenBy: "Rebecca Klein (Plaintiffs' Executive Committee)",
  defendingBy: "Jordan Whitfield / Priya Raman (Calloway & Reyes LLP)",
  location: "Meridian Fluorochem Corp., 1800 Industrial Parkway, Decatur, IL — Boardroom",
  volume: 1,
  pages: 231,
  status: "transcribed",
  exhibits: [
    { id: "Pryce-1", description: "Pryce email, 'RE: Whitfield final' — 'keep to the four of us' (15 Mar 2001)", bates: "MFC-0041882" },
    { id: "Pryce-2", description: "Pryce email to Kaine, 'RE: timing — commercial consequences' (19 Mar 2001)", bates: "MFC-0041920" },
    { id: "Pryce-3", description: "Pryce email, 'RE: MSDS revision — keep the language as is' (4 Apr 2001)", bates: "MFC-0041942" },
    { id: "Pryce-4", description: "Pryce email, 'RE: bioassay proposal — budget' (11 Apr 2001)", bates: "MFC-0041948" },
    { id: "Pryce-5", description: "Aqua-Guard 2001–2002 marketing plan deck (1 May 2001)", bates: "MFC-0041955" },
    { id: "Pryce-6", description: "Pryce email, 'RE: Marketing plan — biodegradable claim' (4 May 2001)", bates: "MFC-0041967" },
    { id: "Pryce-7", description: "Pryce email, 'Do not put this in email' (9 Jul 2002)", bates: "MFC-0052217" },
    { id: "Pryce-8", description: "Pryce response to NAVSEA, MIL-F-24385F qualification (7 Oct 2002)", bates: "MFC-0052238" },
    { id: "Pryce-9", description: "Board pre-read — fluorosurfactant strategy (15 Jun 2001)", bates: "MFC-0041977" },
    { id: "Pryce-10", description: "Aqua-Guard C6 transition timeline (19 Jun 2006)", bates: "MFC-0052251" },
    { id: "Pryce-11", description: "Voss email, 'RE: Marketing plan' — 'Slide 8 is false' (4 May 2001)", bates: "MFC-0041964" },
    { id: "Pryce-12", description: "Board minutes excerpt (20 Jun 2001)", bates: "MFC-0041978" },
  ],
  transcript: [
    qa(5, 8, "Please state your name.", "Alan Thomas Pryce."),
    qa(5, 14, "Mr. Pryce, what was your position in 2001?", "Vice President, Fire Suppression Products. I had the Aqua-Guard line, the hardware line, and the government sales group."),
    qa(6, 5, "To whom did you report?", "The CEO, Douglas Ferris."),
    qa(6, 12, "Who reported to you?", "Nadia Brooks in Product Stewardship, the sales directors, marketing under Karen Liu, and the MilSpec program office."),
    qa(9, 3, "Did Ms. Voss report to you?", "No. Helen was in Product Safety, under Greg Hale. Her group did work for my business unit."),
    qa(12, 17, "How large was the Aqua-Guard business in 2000?", "About 4.2 million gallons and roughly $61 million in revenue. It was the most profitable line in the company."),
    qa(13, 6, "What fraction went to the military?", "The Navy contract was about 35 percent by volume. Air Force and Army through the DLA schedule, another 15."),
    qa(18, 1, "When did you first learn of the Whitfield 90-day results?", "Helen's email. March 14, 2001. I read it that night."),
    qa(18, 10, "Exhibit 1 is your reply the next day. You wrote, 'please keep the report and the summary to the four of us. Do not forward it to the plant, to marketing, or to the Navy program office.' Why?", "Because a toxicology report is not something you circulate before the people who understand it have decided what it means. I did not want a garbled version reaching customers.", { exhibit: "Pryce-1", flags: ["key"] }),
    qa(19, 2, "Did you ever restrict the distribution of the Whitfield report?", "I did not restrict it. I asked that it stay within the working group until we had met on Friday.", { flags: ["contradiction", "evasive"], note: "'keep to the four of us … do not forward' (MFC-0041882) is a restriction on distribution. Also compare Voss 44:13 (Alan said report should not go outside the group)." }),
    qa(19, 15, "Is asking that a document not be forwarded a restriction on its distribution?", "You can call it what you like. It was a request for a few days.", { objection: obj(WHITFIELD, "argumentative"), flags: ["evasive"] }),
    qa(20, 9, "Did the Navy program office ever receive the Whitfield report?", "Not the report. NAVSEA received a summary of the findings in October 2002 in connection with the qualification renewal."),
    qa(20, 20, "That is nineteen months after you received it?", "That sounds right."),
    qa(26, 4, "In Exhibit 1 you also wrote, 'We sold 4.2 million gallons of Aqua-Guard last year on the strength of the existing data package.' What was the existing data package?", "The 1993 28-day study, the aquatic toxicity work, and the MilSpec qualification data."),
    qa(26, 18, "Did the existing data package include any information on persistence or bioaccumulation of the fluorosurfactant?", "The 28-day study had a recovery arm. I would have to look at what it said."),
    qa(31, 7, "Exhibit 2 is your email to Rob Kaine dated March 19, 2001, subject 'timing of any submission.' Did you write it?", "Yes.", { exhibit: "Pryce-2" }),
    qa(31, 14, "You wrote, 'If a substantial-risk notice on our surfactant shows up in the EPA docket in April, every one of those customers will see it.' What customers?", "The Navy re-qualification, Tidewater, Savannah, the two Gulf refineries. The renewals that were coming up."),
    qa(32, 5, "And you wrote, 'If there is a defensible path that involves doing the bioassay first and reporting when we actually know something, that is the path I want.' Correct?", "Correct.", { flags: ["admission", "key"] }),
    qa(32, 14, "Was that path taken?", "Legal made the reporting decision. I was not part of it.", { flags: ["evasive"] }),
    qa(33, 1, "You were copied on Mr. Kaine's advice of March 19, were you not?", "I was copied.", { objection: obj(WHITFIELD, "privilege", "The witness may confirm receipt. He may not disclose the content of Mr. Kaine's advice."), flags: ["privilege"] }),
    qa(33, 12, "Did the commercial considerations you described in Exhibit 2 play any role in the decision not to file an 8(e) notice in 2001?", "I cannot speak to what Legal considered. I told them the commercial picture. That was my job.", { objection: obj(WHITFIELD, "speculation"), flags: ["evasive", "key"] }),
    qa(39, 8, "Exhibit 4, April 11, 2001. 'I will sign the bioassay. I will not sign $1.62M.' Did you write that?", "Yes.", { exhibit: "Pryce-4" }),
    qa(39, 17, "Was budget a factor in the design of the two-year bioassay?", "Budget was not a factor in the design. The design was Whitfield's recommendation. Cost was a factor in what we did in that fiscal year.", { flags: ["contradiction", "key"], note: "MFC-0041948: 'Three groups, not four, and drop the 12-month interim sacrifice … that takes it to about $920K.' Budget drove design. Voss 49:8 confirms." }),
    qa(40, 6, "Your email says, 'Three groups, not four, and drop the 12-month interim sacrifice. Whitfield told Paul on the phone that takes it to about $920K.' Is dropping a dose group a design change?", "It is a design choice within a scientifically valid range. Whitfield agreed three groups gives you a NOAEL.", { objection: obj(WHITFIELD, "form"), flags: ["evasive"] }),
    qa(40, 18, "Who chose three groups instead of four?", "I approved three. Whitfield said it was acceptable."),
    qa(41, 4, "Did Ms. Voss tell you the reduced design could not characterize the low-dose response?", "She may have. Helen had a lot of views about the design.", { flags: ["evasive"] }),
    qa(47, 2, "Exhibit 3, April 4, 2001, the MSDS. You wrote that you were not going to approve an MSDS that says the product 'accumulates in the body' on the strength of 'one rat study that our own toxicologist says is preliminary.' Which toxicologist?", "Helen Voss.", { exhibit: "Pryce-3" }),
    qa(47, 15, "When did Ms. Voss tell you the study was preliminary?", "At the Friday meeting. She said she had not finished her review of the individual animal data."),
    qa(48, 3, "Did she use the word 'preliminary'?", "I do not remember her exact words. That was the substance."),
    qa(48, 12, "The same email says 'Legal has decided [it] does not need to go to EPA.' As of April 4, 2001, had Legal decided that?", "Martin had told me the March analysis concluded no filing was required at that time. Yes.", { objection: obj(WHITFIELD, "privilege", "Instruct the witness not to disclose the substance of the legal analysis. He may answer whether a decision had been communicated to him."), flags: ["privilege", "key"] }),
    qa(49, 1, "Who decided to keep Section 12 as 'has not been determined'?", "I did."),
    qa(49, 8, "Did Mr. Hale participate in that decision?", "Greg was copied. It was my call.", { flags: ["key"] }),
    qa(55, 10, "Exhibit 5 is the 2001–2002 marketing plan. Slide 8 describes MF-3 as a 'different, biodegradable fluorosurfactant.' Who wrote Slide 8?", "Karen Liu's group, with input from sales.", { exhibit: "Pryce-5" }),
    qa(55, 20, "Exhibit 11 is Ms. Voss's email saying 'Slide 8 is false.' Did you read it?", "Yes.", { exhibit: "Pryce-11" }),
    qa(56, 5, "Was Slide 8 false?", "It was inaccurate as to chemistry. 'Biodegradable' was a term the industry used loosely. We revised it.", { flags: ["admission", "key"] }),
    qa(56, 16, "Exhibit 6 is your reply. You wrote, 'Legal will look at the claims before anything goes to print.' Did the deck go to print?", "A revised version went to the sales force in June. Slides 5 and 8 were changed.", { exhibit: "Pryce-6" }),
    qa(57, 4, "Do you have the revised version?", "I assume it was produced. I have not looked."),
    qa(57, 12, "Was the word 'biodegradable' removed?", "I believe it was changed to 'readily biodegradable hydrocarbon surfactant system.' I would have to see it.", { flags: ["evasive"] }),
    qa(64, 7, "Exhibit 9 is your board pre-read from June 2001. Page 2 says, quote, 'the toxicology profile of MF-3 is well characterized and supports continued sale.' Was that accurate?", "In June 2001, yes. We had the 90-day study, we had commissioned the two-year study, and the plant exposures were well below the NOAEL.", { exhibit: "Pryce-9" }),
    qa(65, 2, "Does the pre-read mention that the material has a half-life in the rat of about 100 days?", "It does not.", { flags: ["admission"] }),
    qa(65, 10, "Does it mention that the recovery animals retained the material?", "No.", { flags: ["admission"] }),
    qa(65, 18, "Exhibit 12, the board minutes. The minutes say 'Mr. Pryce reported that the recent rat study raised no issues requiring regulatory action.' Did you say that?", "The minutes are a summary. I told the board that Legal had reviewed the study and that no filing was required. That is what I understood.", { exhibit: "Pryce-12", flags: ["key"] }),
    qa(72, 14, "Let's go to July 2002. Exhibit 7. 'Do not put this in email. Not the recommendations, not the numbers, not the farm.' Why did you write that?", "Because Greg had sent a groundwater interpretation to a wide distribution before anyone had reviewed it. The numbers were preliminary and the recommendations were Greg's personal views.", { exhibit: "Pryce-7", flags: ["key"] }),
    qa(73, 6, "The email was to you and Mr. Suarez. Is that a wide distribution?", "Nadia was on it too. I took her off.", { flags: ["evasive"] }),
    qa(73, 14, "Were the numbers preliminary? The Beacon report was a final laboratory report.", "The interpretation was preliminary.", { flags: ["contradiction"], note: "Position inconsistency: Pryce characterizes 'Do not put this in email' as concern about preliminary numbers; the email itself says nothing goes to the state 'until Legal has looked at it' (MFC-0052217). Hale 50:16 corroborates." }),
    qa(74, 2, "You also wrote, 'Nothing goes to the state or to the city until Legal has looked at it. That is not a no, it is a not yet.' Correct?", "Correct."),
    qa(74, 10, "How long did 'not yet' last?", "The city was notified in October."),
    qa(74, 17, "And the state?", "The formal submission was in November, in response to their request."),
    qa(80, 5, "Was there any business reason to delay notifying the City of Decatur?", "No business reason. Legal wanted another round of data so we were not reporting a single result.", { objection: obj(WHITFIELD, "privilege", "The witness may not disclose the reasons given by counsel."), flags: ["privilege", "key"] }),
    qa(88, 12, "Exhibit 8 is your October 2002 response to Commander Whitcomb at NAVSEA. Item 2 says Meridian 'provided a summary of the 90-day study to EPA in June 2001.' Is that accurate?", "Martin told me a summary went to EPA in response to the voluntary data request. I relied on that.", { exhibit: "Pryce-8" }),
    qa(89, 3, "Did you review the submission to EPA before you wrote to the Navy?", "No."),
    qa(89, 10, "Item 3 says, 'Meridian has not filed a section 8(e) notice to date.' Was that accurate on October 7, 2002?", "Yes. The notice went in later that month.", { flags: ["admission"] }),
    qa(90, 1, "So when you wrote to the Navy, you knew a notice was about to be filed and did not say so?", "I said we 'may make a submission in connection with data from the two-year study.' That was accurate.", { objection: obj(WHITFIELD, "argumentative"), flags: ["evasive", "key"] }),
    qa(90, 14, "The 12-month interim showing liver tumors had been in Meridian's hands since September 11. Did you mention the tumors to the Navy?", "Not in that letter.", { flags: ["admission", "key"] }),
    qa(98, 8, "Exhibit 8 also says the product literature and MSDS were 'revised in August 2001 to reflect the 90-day study.' What was revised?", "Section 11 was revised to say 'eliminated slowly.' The runoff guidance was added."),
    qa(98, 19, "In April 2001 you struck 'may accumulate' from the same section. Was 'eliminated slowly' a full reflection of the 90-day study?", "It reflected what we knew.", { flags: ["evasive"] }),
    qa(106, 3, "Exhibit 10 is the C6 transition timeline from June 2006. Why did Meridian move to a C6 fluorosurfactant?", "Regulatory direction from EPA, customer demand, and the 2005 bioassay result. All three."),
    qa(106, 15, "Was the 2005 bioassay result a reason?", "It was one reason. Yes.", { flags: ["admission"] }),
    qa(114, 9, "Between March 2001 and June 2006, did Meridian ever tell its AFFF customers that the fluorosurfactant was persistent and bioaccumulative?", "The February 2010 customer letter says that. Before that, the MSDS said 'eliminated slowly.'"),
    qa(115, 1, "So the answer to my question is no?", "Not in those words, no.", { flags: ["admission", "key"] }),
    qa(127, 6, "Did you receive a bonus in 2001?", "Yes.", { objection: obj(WHITFIELD, "relevance") }),
    qa(127, 12, "Was any part of it tied to Aqua-Guard revenue?", "Business unit performance was one component. Yes."),
    qa(140, 18, "Have you spoken with Mr. Hale about his testimony?", "No. Counsel told me not to."),
    qa(152, 4, "Mr. Pryce, do you agree that in March 2001 Meridian had information that its fluorosurfactant was toxic to the liver and very persistent, and chose not to tell EPA, the Navy, or its customers?", "I do not agree with the way you put it. We had a study, we commissioned a bigger study, and Legal made the reporting decision.", { objection: obj(WHITFIELD, "form", "Compound, argumentative, and mischaracterizes the testimony."), flags: ["key"] }),
    qa(153, 2, "Did you tell EPA?", "No."),
    qa(153, 7, "Did you tell the Navy?", "Not until 2002."),
    qa(153, 12, "Did you tell your customers?", "Not in 2001.", { flags: ["admission", "key"] }),
    // Examination by defending counsel
    qa(210, 5, "Mr. Pryce, Jordan Whitfield. Did Meridian conduct the two-year bioassay?", "Yes. It started in 2001 and finished in 2005. It cost about $1.1 million in the end.", { objection: obj(KLEIN, "form", "Leading.") }),
    qa(210, 16, "Did Meridian file an 8(e) notice when the interim results showed tumors?", "Yes, in October 2002. Within about six weeks of receiving the interim."),
    qa(214, 3, "Did any customer ever ask Meridian, before 2002, whether the fluorosurfactant was persistent?", "Macon County asked about environmental fate in April 2001. We answered. Nobody else asked.", { objection: obj(KLEIN, "relevance") }),
    qa(219, 8, "Was the C6 transition completed?", "Yes. Aqua-Guard 3 and 6 were discontinued in 2008 and replaced by Aqua-Guard C6."),
    qa(227, 1, "Nothing further.", "(Whereupon, at 4:51 p.m., the deposition was concluded.)"),
  ],
};
