import type { Deposition } from "@/lib/types/domain";
import { DEMO_DEPOSITIONS } from "../ids";
import { CUST, DEFENDED_BY, M, TAKEN_BY, tagged } from "./people";
import { assemble, DEFENSE_ATTORNEY as DA, EXAMINING_ATTORNEY as EA, obj, type DocIndex, type ExhibitSpec, type RawQA } from "./depo-helpers";

/**
 * Deposition of Lena Marsh (FICTIONAL), Director, App Store Policy. Vol. I. Contains the late-qualification pair:
 * an apparent admission at 18:4 about the purpose of the anti-steering rule and her own qualification at 97:3.
 */

export const MARSH_CITES = {
  admission: { page: 18, line: 4 },
  qualification: { page: 97, line: 3 },
  commissionCost: { page: 64, line: 10 },
  superAppsSafety: { page: 52, line: 4 },
} as const;

const EXHIBITS: ExhibitSpec[] = [
  { id: "Marsh-1", slug: "a01", page: 14, description: "annotated excerpt of the developer agreement purchase provisions (Sept. 2016)", recognize: "Yes. It's the training annotation my team maintained for App Review." },
  { id: "Marsh-2", slug: "a02", page: 20, description: "Ames email forwarding Kitebird's request to show web pricing (8 May 2017)", recognize: "Yes, I received it." },
  { id: "Marsh-3", slug: "a03", page: 21, description: "Marsh reply, 'RE: FW: Kitebird — request to show web pricing in app' (9 May 2017)", recognize: "Yes. That's my email." },
  { id: "Marsh-4", slug: "a07", page: 30, description: "draft v1 of the anti-steering rationale memo (17 Jul 2018)", recognize: "It looks like an early draft of my memo." },
  { id: "Marsh-5", slug: "a05", page: 33, description: "final anti-steering rationale memo (19 Jul 2018)", recognize: "Yes. That's the final memo." },
  { id: "Marsh-6", slug: "s02", page: 44, description: "Marsh memo, 'Mini-apps inside host apps: policy position' (4 Oct 2018)", recognize: "Yes, I wrote it." },
  { id: "Marsh-7", slug: "s03", page: 47, description: "Whitaker reply on mini-apps (5 Oct 2018)", recognize: "Yes." },
  { id: "Marsh-8", slug: "k05", page: 58, description: "Marsh memo, 'Commission rate: developer sentiment and policy options' (10 Sep 2019)", recognize: "Yes, that's my memo to Graham." },
  { id: "Marsh-9", slug: "k03", page: 66, description: "App Store services FY2017 contribution summary (14 Feb 2018)", recognize: "No. I don't believe I've seen this before today.", recipients: "I don't know. It's a finance document." },
  { id: "Marsh-10", slug: "k07", page: 74, description: "Marsh email, 'Small Business Program — announcement messaging' (3 Nov 2020)", recognize: "Yes." },
  { id: "Marsh-11", slug: "g02", page: 112, description: "Lee memo, 'Game streaming: per-title review vs. catalog apps' (19 Nov 2019)", recognize: "I received it. I read it at the time." },
  { id: "Marsh-12", slug: "a09", page: 131, description: "Marsh email, 'Link-out entitlement — conversion tracking' (20 Jan 2022)", recognize: "Yes." },
  { id: "Marsh-13", slug: "x01", page: 150, description: "consumer switching research summary (30 Aug 2017)", recognize: "Yes. My team circulated it for the offsite.", author: "Consumer Insights did the study. My team wrote the summary and the implications section." },
  { id: "Marsh-14", slug: "pr01", page: 156, description: "services planning offsite deck, 'Retention and the platform' (Sept. 2017)", recognize: "I attended the offsite. I've seen the deck.", author: "Graham's staff put it together." },
];

const RAW: RawQA[] = [
  [5, 2, "(Appearances noted on the record. The witness was sworn.) Good morning. Please state your full name for the record.", "Lena Marie Marsh."],
  [5, 12, "Ms. Marsh, you understand you are testifying under oath as if in a court of law?", "I do."],
  [6, 4, "Is there any reason, medical or otherwise, that you cannot give complete and accurate testimony today?", "No."],
  [6, 10, "Who is your employer?", "Apple. I'm Director of App Store Policy."],
  [7, 2, "How long have you held that position?", "Director since 2016. Before that I was a senior manager on the same team from 2014."],
  [7, 15, "To whom do you report?", "Graham Whitaker, Vice President of App Store Business."],
  [8, 3, "How many people are on your team?", "About fourteen policy analysts and two program managers."],
  [9, 6, "What does App Store Policy do?", "We interpret and maintain the review guidelines, handle escalations from App Review and Developer Relations, and advise on changes to the rules."],
  [10, 12, "Is App Review part of your organization?", "No. App Review is a separate team under Jae Park. They make the review decisions; we set and interpret the policy they apply."],
  [11, 3, "What did you do to prepare for today?", "I met with counsel twice and reviewed some documents.", { objection: obj(DA, "privilege", "Caution the witness not to disclose the content of communications with counsel.") }],
  [11, 18, "Which documents did you review?", "Some of my emails and memos. I couldn't tell you the Bates numbers."],
  [12, 8, "Have you testified before, in a deposition or in court?", "No."],
  [16, 5, "In general terms, what is the in-app purchase requirement?", "Apps that sell digital goods or services for use in the app have to sell them through In-App Purchase, which is our payment system."],
  [17, 2, "And what do you understand by the anti-steering rule?", "The guideline that apps can't include buttons, links or other calls to action that direct customers to purchasing mechanisms other than In-App Purchase."],
  [17, 19, "Does that include a statement of a price available elsewhere, with no link?", "Under our interpretation, yes."],
  [18, 4, "The purpose of the anti-steering provision was to prevent developers from telling users they could pay less outside the app, correct?", "Yes. That was the purpose — to keep the purchase in the app.", { flags: ["admission", "key"], note: "Early admission on purpose. Qualified by the witness at 97:3; both passages must be preserved and cited together." }],
  [18, 17, "Is that still your understanding today?", "Yes.", { flags: ["admission"] }],
  [19, 3, "Keeping the purchase in the app keeps the commission, doesn't it?", "When a purchase happens in the app, the commission applies.", { objection: obj(DA, "form") }],
  [22, 5, "In Exhibit Marsh-3 you wrote 'the price comparison does the work for them and the purchase leaves the app.' What did you mean?", "That if users saw a lower price on the web, many of them would buy there instead of in the app.", { flags: ["admission", "key"] }],
  [22, 18, "You also wrote 'Don't get into why.' Why did you tell Mr. Ames not to explain the reason?", "Because explanations get quoted back to us and argued with. The guideline speaks for itself.", { flags: ["evasive"] }],
  [24, 2, "Does your May 9, 2017 email mention user trust, fraud or refunds anywhere?", "Not in that email."],
  [24, 14, "Did Kitebird ever submit the one-line text?", "I believe they didn't, after Victor's response."],
  [26, 7, "How often did escalations like Kitebird's reach you in 2017?", "A few a month. Mostly reader and subscription apps."],
  [31, 5, "Turn to paragraph 3 of Exhibit Marsh-4: 'The main effect of consistent enforcement is to protect the commission on digital purchases.' Did you write that?", "Yes, in a first draft.", { flags: ["admission", "key"] }],
  [31, 20, "Why did that sentence change in the final version?", "I revised it after receiving comments."],
  [32, 4, "Comments from whom?", "(Instructed not to answer.)", { objection: obj(DA, "privilege", "To the extent the answer would reveal advice of counsel, I instruct the witness not to answer."), flags: ["privilege"] }],
  [32, 15, "Setting aside counsel, did anyone else comment on paragraph 3?", "Not that I recall."],
  [34, 6, "The final memo, Exhibit Marsh-5, paragraph 3, says 'Consistent enforcement also protects the commission on digital purchases. We should not pretend otherwise internally; externally, the trust rationale is the one we explain.' Did I read that correctly?", "That's what it says."],
  [35, 1, "So the reason given to developers externally was different from the reason discussed internally?", "Both reasons were true. We led externally with the one that applies to every app.", { flags: ["key"] }],
  [38, 10, "Paragraph 4 says 1,140 submissions were rejected under the guideline in the first half of 2018, 61% of them reader or subscription apps. Is that consistent with your recollection?", "Yes. Those numbers came from App Review."],
  [40, 2, "Why were reader and subscription apps the majority?", "They're the apps with a business outside the app. They have the most reason to mention it."],
  [45, 3, "In Exhibit Marsh-6 you identified 'store-within-a-store' and platform neutrality — that 'switching gets easier' — as concerns and wrote that they 'are the business reasons and should stay internal.' Is that right?", "Yes, I wrote that.", { flags: ["admission", "key"] }],
  [46, 9, "Did anyone tell you it was inappropriate to consider how easy it is for users to switch phones?", "Not that I recall."],
  [48, 2, "Mr. Whitaker wrote, 'If they can live with it, fine — they won't be able to.' Did you understand he expected Kitebird could not comply?", "You'd have to ask Graham what he meant.", { flags: ["evasive"] }],
  [50, 11, "Did Kitebird's mini-program directory ever launch on the platform?", "Not as a directory. They launched a small number of individually reviewed mini-programs."],
  [52, 4, "Was the commission part of your thinking on the mini-app directory restriction?", "No. The directory restriction was about safety and review. Commission never came into it.", { flags: ["contradiction", "key"], note: "Compare Marsh-6 ({B:s02}), concerns 1–2 ('store-within-a-store … we do not collect on')." }],
  [52, 20, "Your memo says a host app would become a channel 'we do not review and do not collect on.' 'Collect on' refers to commission, doesn't it?", "It refers to the fact that purchases wouldn't go through In-App Purchase.", { flags: ["evasive"] }],
  [55, 8, "Let's turn to the commission. Who sets the commission rate?", "Senior leadership. It's not a policy-team decision."],
  [56, 2, "Has the standard 30% rate changed since you joined the team?", "The standard rate hasn't. The subscription rate after the first year and the Small Business Program rate are 15%."],
  [59, 8, "In Exhibit Marsh-8 you recommended against relaxing the limits on communicating other purchase options because 'that change affects the entire commission base, not a tier.' Correct?", "Yes.", { flags: ["admission"] }],
  [60, 3, "You recommended option B — a reduced rate for small developers — as 'low revenue impact, strong signal.' A signal to whom?", "To developers, and to anyone watching. It showed we listened."],
  [64, 10, "Did anyone in Finance ever tell you how the 30% rate compared to the cost of operating the store?", "Yes. Finance told us the commission roughly tracked the cost of running the store and the platform. That was my understanding throughout.", { flags: ["contradiction", "key"], note: "Errata (served 28 May 2026) changes 'Finance told us' to 'I understood from someone in Finance'. Contradicted by Okoro 41:3 and by the FY2017 contribution summary ({B:k03})." }],
  [65, 2, "Who in Finance?", "I believe it came up in a planning discussion. I don't remember who.", { flags: ["evasive"] }],
  [67, 4, "Had you seen the FY2017 contribution summary before today?", "No."],
  [67, 14, "It shows direct operating costs of 14.8 against commission revenue of 100. Does that change your understanding that the commission roughly tracked costs?", "I'd have to understand how it was prepared.", { objection: obj(DA, "foundation") }],
  [68, 6, "Paragraph 5(a) says 'The commission rate is not set by reference to cost.' Do you have any basis to disagree?", "I don't have a basis either way. I'm not in Finance."],
  [75, 3, "You copied Ms. Cole on Exhibit Marsh-10. Were you asking her for legal advice in that email?", "No. I was copying her so she had the timing.", { flags: ["key"], note: "Privilege-CC: counsel copied on business messaging; supports challenge to defendant's log." }],
  [75, 15, "Point 4 of your email: 'If asked whether the program responds to regulators or litigation, the answer is that we have been listening to small developers for years.' Was that accurate?", "We had been hearing from small developers for years.", { objection: obj(DA, "form") }],
  [76, 2, "What did Ms. Cole tell you about how the program should be described?", "(Instructed not to answer.)", { objection: obj(DA, "privilege", "Instruct the witness not to answer."), flags: ["privilege"] }],
  [78, 9, "Point 2 says to say 'the vast majority of developers' until Finance signs off on the count. Did Finance sign off?", "I believe the final count was about 98 percent."],
  [81, 5, "Did the Small Business Program change the commission paid on most consumer spending?", "No. Most spending is with larger developers, and their rate didn't change."],
  [84, 12, "Were you involved in the associated-developer rules?", "Yes. My team drafted the eligibility language with the agreement team."],
  [88, 3, "Turning to reader apps. What is the account-link entitlement?", "Reader apps can include one link to their website for account management, subject to conditions."],
  [90, 17, "Why was the entitlement limited to reader apps?", "Reader apps don't sell digital content in the app, so the link doesn't bypass In-App Purchase for anything sold in the app."],
  [93, 6, "(Recess taken 12:02 p.m. to 1:05 p.m.)", "(Back on the record.)"],
  [97, 3, "Ms. Marsh, before the lunch break you told your counsel you wanted to clarify an earlier answer. Go ahead.", "Yes. This morning, at page 18 or so, when I was asked about the purpose of the anti-steering provision, I said the purpose was to keep the purchase in the app. That's incomplete. The main purpose, as the 2018 rationale memo says, is user trust — one account, one set of refund rights, parental controls and protection from payment fraud. Protecting the commission is an effect of enforcing it, not the reason for it.", { flags: ["key"], note: "Late qualification of 18:4 (made after a break with counsel). Preserve both; compare Marsh-3 ({B:a03}) and Marsh-4 draft para. 3 ({B:a07})." }],
  [98, 1, "Nothing in your May 2017 email to Mr. Ames — Exhibit Marsh-3 — mentions user trust, correct?", "Correct.", { flags: ["admission"] }],
  [98, 14, "And your first draft of the rationale memo said the 'main effect' of enforcement was to protect the commission?", "The first draft said that. The final did not."],
  [99, 2, "Between your answer at page 18 and now, did you discuss your testimony with anyone?", "I spoke with my counsel at lunch.", { objection: obj(DA, "privilege", "She can answer yes or no; the content is privileged.") }],
  [99, 16, "Did you ask to clarify your answer before or after that conversation?", "After.", { flags: ["key"] }],
  [104, 4, "Has App Review ever approved an app that told users a lower price was available on the web?", "Not knowingly under the current guideline. Mistakes happen."],
  [106, 11, "What happens when App Review finds one after approval?", "The next update is rejected until the statement is removed."],
  [113, 4, "Mr. Lee wrote that per-title review for streamed games was 'unworkable,' and 'several people here see that as a feature, not a bug.' Were you one of those people?", "No. I thought per-title review was a legitimate quality measure."],
  [114, 10, "Did you ever express the view that keeping catalog streaming off the platform was a benefit?", "Not that I recall."],
  [116, 2, "Did the streaming guideline adopted in September 2020 follow option B in Mr. Lee's memo?", "Broadly, yes. Each streamed game needed its own listing."],
  [119, 9, "Did any catalog streaming service launch a single native app after that?", "Not in that period, to my knowledge. They used the web."],
  [124, 3, "Were you consulted on the NFC or wallet access questions?", "No. That's a different organization."],
  [126, 15, "Or on messaging with other platforms?", "No."],
  [132, 2, "In Exhibit Marsh-12 you wrote that if conversion through the link is low, 'the entitlement is a pressure valve we can point to.' What did you mean?", "If few people used the link, we could show regulators we had offered an option without it changing much.", { flags: ["admission", "key"] }],
  [132, 20, "Ms. Cole and Mr. Ames are copied. Were you requesting legal advice from Ms. Cole in that email?", "No. I copied them for visibility.", { flags: ["key"], note: "Second privilege-CC admission (counsel copied on a business instruction to Finance)." }],
  [134, 8, "The attached scenario tab models fees of 20, 24 and 27 percent on purchases made through the link. Who asked for those scenarios?", "I asked Finance to include them so we'd understand the range. No decision was made."],
  [137, 5, "Did you receive the monthly conversion tracking you asked for?", "For a while. Conversion through the link was low."],
  [151, 6, "The implications section of Exhibit Marsh-13 says 'Purchases that live inside our store travel with the user only within our platform; purchases made on the web travel anywhere.' Your team wrote that?", "My team wrote the implications. I approved them.", { flags: ["admission"] }],
  [152, 3, "What does 'travel with the user' mean?", "If you switch phones, apps and in-app content bought in our store don't come with you. A purchase on the developer's website usually does."],
  [157, 3, "Slide 3 of Exhibit Marsh-14: 'Purchases made in the store stay with the platform. Web purchases travel.' Was keeping purchases in the store discussed at the offsite as a retention strategy?", "It was discussed. It was one slide in a long offsite.", { flags: ["key"] }],
  [158, 14, "Did your team change any policy after the offsite?", "Not because of the offsite, no."],
  [163, 9, "Is it fair to say the anti-steering guideline makes it harder for users to learn about lower prices on developers' websites?", "It limits what apps can say inside the app. Users can find prices other ways.", { objection: obj(DA, "form") }],
  [166, 2, "Do you know what share of users look for prices outside the app?", "No."],
  [170, 1, "(Examination by counsel for defendant.)", "(Mr. Mercer examining.)"],
  [181, 4, "Ms. Marsh, has App Review rejected apps whose external payment flows were used for fraud?", "Yes, regularly — subscription traps, fake payment pages, apps that took payment and never delivered."],
  [182, 12, "Do those cases inform the purchase guidelines?", "Yes. They're a big part of why the rules exist."],
  [184, 9, "Is user trust a real reason for the anti-steering guideline?", "Yes.", { objection: obj(EA, "form", "Leading.") }],
  [186, 3, "Were you ever instructed to enforce the guideline differently for large developers?", "No. Same rules for everyone."],
  [190, 2, "(Further examination by Ms. Castell.) Ms. Marsh, your final 2018 memo says consistent enforcement 'protects the commission on digital purchases,' correct?", "Yes."],
  [190, 15, "And you wrote that the trust rationale is the one explained 'externally'?", "Yes, that's what it says.", { flags: ["admission"] }],
  [193, 6, "Did any fraud-prevention study support the ban on text-only price statements with no link?", "Not a specific study that I know of."],
  [212, 10, "Nothing further. (Whereupon, at 5:48 p.m., the deposition was adjourned.)", "(Signature reserved.)"],
];

export function buildMarshDeposition(ix: DocIndex): Deposition {
  const { transcript, exhibits } = assemble(RAW, EXHIBITS, ix);
  return tagged<Deposition>({
    id: DEMO_DEPOSITIONS.appStorePolicy, matterId: M, witnessId: CUST.marsh.id, witnessName: CUST.marsh.name, witnessTitle: `${CUST.marsh.title} (fictional witness)`,
    date: "2026-04-14", takenBy: TAKEN_BY, defendingBy: DEFENDED_BY, location: "Hartwell & Pryor LLP (fictional), San Francisco, CA — Conference Room 21A", volume: 1, pages: 214,
    status: "reviewed", transcript, exhibits,
    aiDigest: {
      summary: "Director of App Store Policy. Authenticated the 2017 Kitebird rejection and the 2018 rationale memo; admitted early that the anti-steering rule's purpose was to keep purchases in the app (18:4), then qualified after the lunch break that user trust is the main purpose (97:3). Testified that Finance told her the commission tracked the cost of the store (64:10), which the Finance lead contradicts.",
      keyAdmissions: [
        "Purpose of anti-steering was to keep the purchase in the app (18:4) — later qualified (97:3).",
        "Wrote that a price comparison 'does the work for them' (22:5).",
        "First draft said the 'main effect' of enforcement is to protect the commission (31:5).",
        "Mini-app memo's store-within-a-store and switching concerns were business reasons kept internal (45:3).",
        "Link entitlement described as a 'pressure valve we can point to' (132:2).",
        "Counsel was only copied on the SBP messaging and link-tracking emails (75:3, 132:20).",
      ],
      themes: ["Anti-steering purpose", "Internal vs. external rationale", "Super apps", "Commission and cost", "Privilege-CC"],
      credibilityNotes: ["Qualification at 97:3 came after a conversation with counsel (99:2–99:16).", "Evasive on who in Finance gave the cost comparison (65:2)."],
      followUps: ["Depose Graham Whitaker on the mini-app hold and 'they won't be able to' (48:2).", "Subpoena the monthly link-conversion tracking (137:5).", "Compare errata at 64:10 with Okoro 41:3."],
    },
  }, { errata: [{ page: 64, line: 10, from: "Finance told us", to: "I understood from someone in Finance", reason: "Clarification", servedAt: "2026-05-28" }] });
}
